name: Pytest

on: [push]

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync --frozen
      - name: Run Tests
        run: uv run pytest
